DROP TABLE bookings;
DROP TABLE items;
DROP TABLE itemrequests;
DROP TABLE users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS itemrequests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255) NOT NULL,
    user_id BIGINT,
    created TIMESTAMP,
    CONSTRAINT pk_itemrequest PRIMARY KEY (id),
    CONSTRAINT fk_requests_to_users FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    user_id BIGINT NOT NULL,
    available BOOLEAN,
    request_id BIGINT REFERENCES itemrequests(id),
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        time_start TIMESTAMP,
                                        time_end TIMESTAMP,
                                        item_id BIGINT REFERENCES items(id),
                                        user_id BIGINT REFERENCES users(id),
                                        status VARCHAR(16),
                                        CONSTRAINT pk_buoking PRIMARY KEY (id)
);